common: &default_settings
  api_key: 'replace me'
  params_filters:
  - password
  host: 'api.airbrake.io'
  enabled: false

development:
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
  enabled: true
